# SPDX-FileCopyrightText: 2024 Ledger SAS
# SPDX-FileCopyrightText: 2026 H2Lab
#
# SPDX-License-Identifier: Apache-2.0

name: Python Unit Tests

on:
  push:
    branches:
    - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'tox.ini'
      - '.github/workflows/unittest.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'tox.ini'
      - '.github/workflows/unittest.yml'

jobs:
  unittest:
    strategy:
      matrix:
          version: ['3.11', '3.12', '3.13', '3.14']
    uses: camelot-os/pipeline-python/.github/workflows/unittest.yml@v1
    with:
      python-version: ${{ matrix.version }}
    secrets: inherit
